# This is a temp compose file for testing db connection, not setup kubernetes yet.
version: "3.9"
services:
  db:
    image: postgres:17
    container_name: gestalto_db_container
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"